version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: docker_postgres_ecommerce
    environment:
      POSTGRES_USER: alyas
      POSTGRES_PASSWORD: Fortnite-1
      POSTGRES_DB: E-Commerce
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # db data volume (important for persistence, when restarting or deleting container)
      - ./backup.dump:/backup/backup.dump # create bind mount (not exist physically inside container, just get linked to host)

volumes:
  pgdata:
