name: CI Pipeline

# tells GitHub to run this workflow when code is pushed to the dev branch
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # donwload the repo into vm

      # print message for demo/testing
      - name: Say Hello
        run: echo "CI is running on dev branch!"
